sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "6"
  - "7"

script:
  - "test $TRAVIS_NODE_VERSION  = '0.6' || npm test"
  - "test $TRAVIS_NODE_VERSION != '0.6' || npm run-script test-coverage"
